apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: null
  name: eks-a-02
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: eks-a-02
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: GitOpsConfig
    name: eks-a-02
  kubernetesVersion: "1.21"
  workerNodeGroupConfigurations:
  - count: 2
status: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  creationTimestamp: null
  name: eks-a-02
spec: {}
status: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  creationTimestamp: null
  name: eks-a-02
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/eks-a-02
      fluxSystemNamespace: flux-system
      owner: legopost
      personal: true
      repository: eks-a-02
status: {}

---
